require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/checks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Check. As you add validations to Check, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Check.create! valid_attributes
      get checks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      check = Check.create! valid_attributes
      get check_url(check)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_check_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      check = Check.create! valid_attributes
      get edit_check_url(check)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Check" do
        expect {
          post checks_url, params: { check: valid_attributes }
        }.to change(Check, :count).by(1)
      end

      it "redirects to the created check" do
        post checks_url, params: { check: valid_attributes }
        expect(response).to redirect_to(check_url(Check.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Check" do
        expect {
          post checks_url, params: { check: invalid_attributes }
        }.to change(Check, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post checks_url, params: { check: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested check" do
        check = Check.create! valid_attributes
        patch check_url(check), params: { check: new_attributes }
        check.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the check" do
        check = Check.create! valid_attributes
        patch check_url(check), params: { check: new_attributes }
        check.reload
        expect(response).to redirect_to(check_url(check))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        check = Check.create! valid_attributes
        patch check_url(check), params: { check: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested check" do
      check = Check.create! valid_attributes
      expect {
        delete check_url(check)
      }.to change(Check, :count).by(-1)
    end

    it "redirects to the checks list" do
      check = Check.create! valid_attributes
      delete check_url(check)
      expect(response).to redirect_to(checks_url)
    end
  end
end
